### ISSUE TITLE
Wrappers do not work with methods of arity 0 

### ISSUE THREAD

**Issue by nilsding** [andreaseger/receptacle#8]
Code says more than 1000 words:

```ruby
require "bundler/inline"

gemfile true do
  source "https://rubygems.org"
  gem "receptacle"
end

module MyRepo
  include Receptacle::Repo

  mediate :clear
  mediate :insert

  module Strategy
    class DB
      def store
        @store || clear
      end

      def clear
        @store = {}
      end

      def insert(id:, value:)
        store[id] = value
      end
    end
  end

  module Wrapper
    class Logger
      def before_clear
        puts "About to clear the db"
      end

      def before_insert(id:, value:)
        puts "Inserting id=>#{id} to db"
        { id: id, value: value }
      end
    end
  end
end

MyRepo.strategy MyRepo::Strategy::DB
MyRepo.wrappers [MyRepo::Wrapper::Logger]

MyRepo.insert(id: 2, value: :something)  # works
MyRepo.clear                             # 🔥
```

Output:

```
[bundler output omitted]
Inserting id=>2 to db
Traceback (most recent call last):
	4: from receptacle-bug.rb:48:in `<main>'
	3: from /Users/nilsding/.rvm/gems/ruby-2.5.0/gems/receptacle-0.3.1/lib/receptacle/method_delegation.rb:13:in `method_missing'
	2: from /Users/nilsding/.rvm/gems/ruby-2.5.0/gems/receptacle-0.3.1/lib/receptacle/method_delegation.rb:13:in `public_send'
	1: from /Users/nilsding/.rvm/gems/ruby-2.5.0/gems/receptacle-0.3.1/lib/receptacle/method_delegation.rb:64:in `block in __define_full_method'
/Users/nilsding/.rvm/gems/ruby-2.5.0/gems/receptacle-0.3.1/lib/receptacle/method_delegation.rb:86:in `__run_wrappers': wrong number of arguments (given 1, expected 2..3) (ArgumentError)
```

---

I guess the problem occurs because the method arguments array is empty, and the splatting inside ` Receptacle::MethodDelegation#__define_full_method` changes the number of arguments passed to `__run_wrappers` from 2 to 1.

**Comment by andreaseger** [comment]
yeah it's a known issue. IIRC it was kinda hard to make this work without making the method delegation code complicated. also agument passing gets kinda weird if the method parameters are arrays.

But feel free to create a PR which adds support for that
